services:
  campaigns-db:
    image: postgres:16
    container_name: campaigns_db_postgres
    environment:
      POSTGRES_DB: Db.Campaigns
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - campaigns_pg_data:/var/lib/postgresql/data
    networks:
      - microsservicos-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Db.Campaigns" ]
      interval: 10s
      timeout: 5s
      retries: 10


  campaigns-api:
    depends_on:
      campaigns-db:
        condition: service_healthy
      dynamodb-local: 
        condition: service_started
    
    
volumes:
  campaigns_pg_data:


networks:
  microsservicos-net:
    name: app-network
    driver: bridge