services:
  campaigns-db:
    image: postgres:16
    container_name: campaigns_db_postgres
    environment:
      POSTGRES_DB: Db.Campaigns
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5439:5432"
    volumes:
      - campaigns_pg_data:/var/lib/postgresql/data
    networks:
      - microsservicos-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Db.Campaigns" ]
      interval: 10s
      timeout: 5s
      retries: 10
      
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - microsservicos-net
    restart: unless-stopped


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - microsservicos-net
      

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - microsservicos-net
    
    # Só no docker-compose.local.yml (override)
    redis-commander:
      image: rediscommander/redis-commander:latest
      environment:
        - REDIS_HOSTS=local:redis:6379
      ports:
        - "8081:8081"
      networks:
        - microsservicos-net
      depends_on:
        - redis


  campaigns-api:
    depends_on:
      campaigns-db:
        condition: service_healthy
      dynamodb-local: 
        condition: service_started
    
    
volumes:
  prometheus-data:
  campaigns_pg_data:


networks:
  microsservicos-net:
    name: app-network
    driver: bridge